[package]
name = "snake"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy  = "0.7.0"
bevy_ecs_tilemap = "0.6.0"
bevy_egui = "0.12.1"
rand = "0.8.4"
